"use strict";
//Making array of countries and printing it in its original order
let countriesToVisit = ["Brazil", "London", "Australia", "Zambia", "Palestine"];
console.log("Printing the array in its original order:");
console.log(countriesToVisit);
console.log("Now printing the countries list copy in alphabetical order:");
console.log(countriesToVisit.slice().sort());
console.log("Printing the array in its original order:");
console.log(countriesToVisit);
console.log("Printing the list copy in reverse alphabetical order:");
console.log(countriesToVisit.slice().sort().reverse());
console.log("Printing the array in its original order:");
console.log(countriesToVisit);
console.log("Now printing the original array in reverse order:");
console.log(countriesToVisit.reverse());
console.log("Now printing the original array in its original order:");
console.log(countriesToVisit.reverse());
console.log("Printing the original array in alphabetical order:");
console.log(countriesToVisit.sort());
console.log("Changing the original array in reverse alphabetical order again:");
console.log(countriesToVisit.reverse());
