var num1 = 20;
var num2 = 30;
console.log("Is num 1 equal to twenty?");
console.log(num1 == 20);
console.log("Is num2 equal to thirty?");
console.log(num2 == 30);
console.log("Num1 is not equal to Num2");
console.log(num1 != num2);
console.log("Is Num1 less than num2?");
console.log(num1 < num2);
console.log("Is num2 greater than num1?");
console.log(num2 > num1);
console.log("Is num 1 equal to fifty?");
console.log(num1 == 50);
console.log("Is num2 equal to twentyfive?");
console.log(num2 == 25);
console.log("Is Num1 equal to Num2?");
console.log(num1 == num2);
console.log("Is Num1 greater than num2?");
console.log(num1 > num2);
console.log("Is num2 less than num1?");
console.log(num2 < num1);
